require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'

exclude_paths = ["spec/**/*", "pkg/**/*", "vendor/**/*", "bundle/**/*" ]
Rake::Task[:lint].clear
PuppetLint::RakeTask.new :lint do |config|
  config.disable_checks = [ '80chars', 'class_parameter_defaults', 'class_inherits_from_params_class' ]
  config.log_format = "%{path}:%{linenumber}:%{check}:%{KIND}:%{message}"
  config.fail_on_warnings = true
  config.relative = true
  config.ignore_paths = exclude_paths
end


desc 'Run syntax, lint, and spec tests.'
task :test => [
         :lint,
         :spec,
     ]
